openapi: 3.0.0
info:
  title: Jarvis
  version: 1.0.0
  contact: {}
paths:
  /models/impira/layoutlm-document-qa:
    post:
      summary: Answer Question About The Document Image
      description: useful when you need an answer for a question based on a document image. The inputs include a document image url and a question.
      parameters: []
      operationId: impira-layoutlm-document-qa
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      tags:
        - VisionDocQA
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
security: []
servers:
  - url: 'https://jarvis.daovous.xyz'
    description: A API for connecting numerous AI models for solving complicated AI tasks
components:
  links: {}
  callbacks: {}
  schemas:
    Query:
      type: object
      properties:
        image:
          type: string
        text:
          type: string
    Response:
      type: object
      properties:
        answer:
          type: string
tags: []