openapi: 3.0.0
info:
  title: Jarvis
  version: 1.0.0
  contact: {}
paths:
  /models/ydshieh/vit-gpt2-coco-en:
    post:
      summary: Generate description from image
      description: useful when you want to do image captioning, or generate description from image, which convert image to text. receives image path or url as input. The input to this tool should be a string, representing the image path or url to generate description.
      parameters: []
      operationId: ydshieh-vit-gpt2-coco-en
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      tags:
        - Image Captioning
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
security: []
servers:
  - url: 'https://jarvis.daovous.xyz'
    description: A API for connecting numerous AI models for solving complicated AI tasks
components:
  links: {}
  callbacks: {}
  schemas:
    Query:
      type: object
      properties:
        image:
          type: string
    Response:
      type: object
      properties:
        text:
          type: string
tags: []