openapi: 3.0.0
info:
  title: Jarvis
  version: 1.0.0
  contact: {}
paths:
  /models/Intel/dpt-large:
    post:
      summary: Image depth estimation using Intel/dpt-large
      description: >-
        useful when you want to do vision depth estimation for an image using
        Intel/dpt-large. The input to this tool should be a string, representing the image url used to depth estimation.
      parameters: []
      operationId: Intel-dpt-large
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      tags:
        - depth estimation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
security: []
servers:
  - url: 'https://jarvis.daovous.xyz'
    description: A API for connecting numerous AI models for solving complicated AI tasks
components:
  links: {}
  callbacks: {}
  schemas:
    Query:
      type: object
      properties:
        image:
          type: string
    Response:
      type: object
      properties:
        generated image:
          type: string
tags: []