openapi: 3.0.0
info:
  title: Jarvis
  version: 1.0.0
  contact: {}
paths:
  /models/espnet/kan-bayashi_ljspeech_vits:
    post:
      summary: Generate Audio From User Input Text
      description: useful when you want to generate an audio/speech from a user input text
      parameters: []
      operationId: espnet-kan-bayashi_ljspeech_vits
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      tags:
        - Text-to-Audio
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
security: []
servers:
  - url: 'https://jarvis.daovous.xyz'
    description: A API for connecting numerous AI models for solving complicated AI tasks
components:
  links: {}
  callbacks: {}
  schemas:
    Query:
      type: object
      properties:
        text:
          type: string
    Response:
      type: object
      properties:
        generated audio:
          type: string
tags: []