openapi: 3.0.0
info:
  title: Jarvis
  version: 1.0.0
  contact: {}
paths:
  /models/runwayml/stable-diffusion-v1-5:
    post:
      summary: Generate Image From User Input Text using stable-diffusion-v1-5
      description: >-
        useful when you want to generate an image from a user input text. like:
        generate an image of an object or something, or generate an image that
        includes some objects. The input to this tool should be a string,
        representing the text used to generate image.
      parameters: []
      operationId: runwayml-stable-diffusion-v1-5
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      tags:
        - text-to-image-endpoint
        - stable-diffusion-v1-5
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
security: []
servers:
  - url: 'http://jarvis.daovous.xyz'
    description: A API for connecting numerous AI models for solving complicated AI tasks
components:
  links: {}
  callbacks: {}
  schemas:
    Query:
      type: object
      properties:
        text:
          type: string
    Response:
      type: object
      properties:
        generated image:
          type: string