openapi: 3.0.0
info:
  title: Jarvis
  version: 1.0.0
  contact: {}
paths:
  /models/mlsd-control:
    post:
      summary: Line Detection On Image
      description: useful when you want to detect the straight line of the image. The input to this tool should be a string, representing the image path or url to generate line image.
      parameters: []
      operationId: mlsd-control
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      tags:
        - image-to-image-endpoint
        - mlsd-control
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
security: []
servers:
  - url: 'https://jarvis.daovous.xyz'
    description: A API for connecting numerous AI models for solving complicated AI tasks
components:
  links: {}
  callbacks: {}
  schemas:
    Query:
      type: object
      properties:
        image:
          type: string
    Response:
      type: object
      properties:
        generated image:
          type: string
tags: []